# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307d5eae48d2e2614a2e9b12fc5e2c80c2c3871d0bb4dc1df9b610d29d876b8c50865e299e7a71d8ee16a5cc0549a3ad7271d68b7f33ba776c6d888a47237ea3

test:
  secret_key_base: a56ef091154395dc350e050ffc16b9a2f2472868037db66c46c8741678eada629c907a2628756ac04b2a9d366181dcc5be2470cfcde9166a5d6670f3b7bb2b54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
